const ResponseCode = Object.freeze({
  SUCCESS: 0,
  ERROR: 1,
  NOT_FOUND: 2,
  INVALID_REQUEST: 3,
  UNAUTHORIZED: 4,
  FORBIDDEN: 5,
  CONFLICT: 6,
  UNPROCESSABLE_ENTITY: 7,
  INTERNAL_SERVER_ERROR: 8,
  SERVICE_UNAVAILABLE: 9,
  GATEWAY_TIMEOUT: 10,
  BAD_GATEWAY: 11,
  REQUEST_TIMEOUT: 12,
  TOO_MANY_REQUESTS: 13,
  PAYLOAD_TOO_LARGE: 14,
  NOT_IMPLEMENTED: 15,
  BAD_REQUEST: 16,
});

export default ResponseCode;
